config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :topics do
    resources :collections_memberships, only: [:create]
  end

  resources :collections
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
# frozen_string_literal: true

class Collection < ApplicationRecord
  has_many :collections_memberships
  has_many :topics, through: :collections_memberships
  belongs_to :user
  validates :name, presence: true
  accepts_nested_attributes_for :collections_memberships, allow_destroy: true
end

app/models/collections_membership.rb
# frozen_string_literal: true

class CollectionsMembership < ApplicationRecord
  belongs_to :topic
  belongs_to :collection
end

app/models/topic.rb
# frozen_string_literal: true

class Topic < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :collections_memberships
  has_many :collections, through: :collections_memberships
  accepts_nested_attributes_for :collections_memberships, allow_destroy: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  validates :username, :email, uniqueness: true
  validates :username, presence: true

  has_many :topics
  has_many :collections
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/collections_controller.rb
# frozen_string_literal: true

class CollectionsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_current_user_collection, only: %i[update edit destroy]

  def index
    @collections = Collection.paginate(page: params[:page], per_page: Rails.configuration.x.results_per_page)
  end

  def show
    @collection = Collection.find(params[:id])
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = current_user.collections.new(collection_params)
    if @collection.save
      redirect_to collections_path
    else
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if @collection.update(collection_params)
      redirect_to collection_path
    else
      render :edit
    end
  end

  def destroy
    @collection.destroy
    redirect_to collections_path
  end

  private

  def set_current_user_collection
    @collection = current_user.collections.find(params[:id])
  end

  def collection_params
    params.require(:collection).permit(
      :name,
      :id,
      collections_memberships_attributes: %i[id collection_id topic_id _destroy]
    )
  end
end

app/controllers/collections_memberships_controller.rb
# frozen_string_literal: true

class CollectionsMembershipsController < ApplicationController
  def create
    @topic = Topic.find(params[:topic_id])

    if @topic.update(topic_params)
      redirect_to topic_path(@topic), notice: 'collection(s) successfully updated'
    else
      redirect_to topic_path(@topic)
    end
  end

  private

  def topic_params
    params.require(:topic).permit(
      collections_memberships_attributes: %i[
        id collection_id topic_id _destroy
      ]
    )
  end
end

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  before_action :authenticate_user!, only: %i[new destroy create edit update]
  before_action :set_current_user_topic, only: %i[update destroy edit]

  def index
    @topics = Topic.paginate(page: params[:page], per_page: Rails.configuration.x.results_per_page)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to topics_path
    else
      render :new
    end
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def destroy
    @topic.destroy
    redirect_to topics_path
  end

  def edit
    render :edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to topic_path
    else
      render :edit
    end
  end

  private

  def set_current_user_topic
    @topic = current_user.topics.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:name, collections_memberships_attributes: %i[collection_id topic_id _destroy])
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/collections/edit.html.erb
<h1>Collection</h1>
<p>Edit collection</p>

<h2> <%= @collection.name %></h2>

<% if @collection.errors.any? %>
  <div>
    <h2>Error:</h2>
    <ul>
    <% @collection.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div>
    <%= form_with model: @collection, local: true, method: :patch, url: collection_path(@collection) do |f| %>

      <%- collections_memberships_lookup = @collection
        .collections_memberships
        .reduce({}) {|memo, cm|
          memo[cm.topic_id] = cm.id
          memo
        } %>

      <%= f.label :name %>
      <%= f.text_field :name, id: 'collection_name' %>

      <% @collection.topics.each_with_index do |topic, index| %>

      <%- collections_topic_id = collections_memberships_lookup.fetch(topic.id, '') %>

      <%= hidden_field_tag "collection[collections_memberships_attributes][#{index}][_destroy]", 1, id: "hidden-destroy-#{topic.id}" %>

      <%= check_box_tag "collection[collections_memberships_attributes][#{index}][_destroy]", 0, collections_topic_id.present? %>

      <%= label_tag "collection[collections_memberships_attributes][#{index}][_destroy]", topic.name %>

      <%= hidden_field_tag "collection[collections_memberships_attributes][#{index}][id]", collections_topic_id %>

      <%= hidden_field_tag "collection[collections_memberships_attributes][#{index}][topic_id]", topic.id %>

      <%= hidden_field_tag "collection[collections_memberships_attributes][#{index}][collection_id]", @collection.id %>

      </br>

    <% end %>

    <%= f.submit 'Update' %>

  <% end %>
</div>

app/views/collections/index.html.erb
<section>
  <h1>Collections</h1>

  <p>Collections of topics on assorted themes</p>

  <table>
    <tr>
      <th>Collections</th>
    </tr>
    <%= will_paginate @collections %>
    <% @collections.each do |collection| %>
    <tr>
      <td> <%= link_to collection.name, collection %> </td>
    </tr>
    <% end %>
  </table>

  <% if user_signed_in? %>
    <%= link_to 'New Collection', new_collection_path %>
  <% end %>

</section>

app/views/collections/new.html.erb
<h1>Collections</h1>
<p>Create a new collection</p>

<% if @collection.errors.any? %>
  <div>
    <h2>Error:</h2>
    <ul>
    <% @collection.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div>
  <%= form_for @collection do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/collections/show.html.erb
<h1><%= @collection.name %></h1>
</br>
<h2>Topics:</h2>
<% @collection.topics.each do |topic| %>
  <%= topic.name %>
  </br>
<% end %>

 <% if @collection.user == current_user %>
  <%= link_to 'Edit Collection', edit_collection_path(@collection.id) %>
  </br>
  <%= button_to 'Delete Collection', collection_path(@collection), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>

app/views/collections_memberships/_manage_collections_memberships_form.html.erb
<% if user_signed_in? %>
  <h3> Add to collection </h3>

  <%= form_with model: @topic, method: :post, url: topic_collections_memberships_path(@topic) do |f| %>

      <%- collections_memberships_lookup = @topic
        .collections_memberships
        .reduce({}) {|memo, cm|
          memo[cm.collection_id] = cm.id
          memo
        } %>

      <% current_user.collections.each_with_index do |collection, index| %>

        <%- collections_topic_id = collections_memberships_lookup.fetch(collection.id, '') %>

        <%= hidden_field_tag "topic[collections_memberships_attributes][#{index}][_destroy]", 1, id: "hidden-destroy-#{index}" %>

        <%= check_box_tag "topic[collections_memberships_attributes][#{index}][_destroy]", 0, collections_topic_id.present? %>

        <%= label_tag "topic[collections_memberships_attributes][#{index}][_destroy]", collection.name %>

        <%= hidden_field_tag "topic[collections_memberships_attributes][#{index}][id]", collections_topic_id %>

        <%= hidden_field_tag "topic[collections_memberships_attributes][#{index}][topic_id]", @topic.id %>

        <%= hidden_field_tag "topic[collections_memberships_attributes][#{index}][collection_id]", collection.id %>

        </br>
      <% end %>

    <%= button_to 'Update' %>
  <% end %>
  </br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toastmasters</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
  </head>

  <body>

    <nav class="nav-wrapper">
      <div class='container'>
        <a href="/" class="brand-logo right"></a>
        <ul class="left">
          <li><%= link_to 'Topics', topics_url %></li>
          <li><%= link_to 'Collections', collections_url %></li>
        </ul>

        <ul class="right">
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Log Out', destroy_user_session_url, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Sign Up', new_user_registration_url %>
            </li>
            <li>
              <%= link_to 'Log In', new_user_session_url %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    </div>
  </body>
</html>

app/views/topics/edit.html.erb
<h1>Topics</h1>
<p>Edit topic</p>

<h2> <%= @topic.name %></h2>

<% if @topic.errors.any? %>
  <div>
    <h2>Error:</h2>
    <ul>
    <% @topic.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div>
  <%= form_for @topic do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
</div>

</br>

<%= link_to 'Back to topics page', topics_path %>

app/views/topics/index.html.erb
<section>
  <div class="section">
    <h2>Topics</h2>
    <p>Feel free to use any of our topics in your own Toastmasters meeting.</p>
  </div>

  <div class="divider"></div>

  <div class="row section">
    <%= will_paginate @topics %>

      <% @topics.each do |topic| %>
        <div class="col s4">
          <div class="card blue-grey lighten-4">
           <%= link_to topic_path(topic) do %>
            <div class="card-content">
              <span class="card-title black-text"> <%= topic.name %> </span>
              <p class="white-text">Author: <%= topic.user.username %> </p>
            </div>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>

    <%= link_to 'New Topic', new_topic_path, class: "waves-effect waves-light btn-large" %>
  </div>
</section>

app/views/topics/new.html.erb
<h1>Topics</h1>
<p>Add a new topic</p>

<% if @topic.errors.any? %>
  <div>
    <h2>Error:</h2>
    <ul>
    <% @topic.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div>
  <%= form_for @topic do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/topics/show.html.erb
<section>
  <h1>Topic:</h1>

  <h2> <%= @topic.name %></h2>
  <p> Author: <%= @topic.user.username %> </p>

  </br>

  <% if @topic.errors.any? %>
    <div>
      <h2>Error:</h2>
      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  </br>

  <% if @topic.user == current_user %>
    <%= button_to 'Delete Topic', topic_path(@topic), method: :delete, data: { confirm: "Are you sure?" } %>
    <%= link_to 'Edit Topic', edit_topic_path(@topic.id) %>
  <% end %>

  </br>

  <%= render "collections_memberships/manage_collections_memberships_form" %>

  <%= link_to 'Back to topics page', topics_path %>

</section>

app/views/welcome/index.html.erb
<div class="section">

  <h1 class="toastmasters center-align">Toastmaster Topics</h1>

  <p class="flow-text">Create and share your table-topic ideas and build collections of your favourites to use during your toastmaster meetings or public speaking workshops </p>

  <div class="divider"></div>

  <div class="row">
    <div class="above-video">
      <div class="col s12">
        <div class="video-container">
          <iframe width="853" height="480" src="//www.youtube.com/embed/Q8TXgCzxEnw?rel=0" frameborder="0" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>

  <div class="divider"></div>

  <div class="row home-page-promo">
    <div class="col s4">
      <h4 class="center-align">Topics</h4>
      <p class="flow-text">View topics created by toastmasters all over the world on every subject you can think of</p>
      <%= link_to 'View Topics', topics_url, class: "waves-effect waves-teal btn-flat" %>
    </div>

    <div class="col s4">
      <h4 class="center-align">Collections</h4>
      <p class="flow-text">Use collections curated by our members and easily theme your next meeting or workshop</p>
      <%= link_to 'View Collections', collections_url, class: "waves-effect waves-teal btn-flat" %>
    </div>

    <div class="col s4">
      <h4 class="center-align">Share</h4>
      <p class="flow-text">Sign up to share your own topics and create collections containing topics from the whole community</p>

      <% if user_signed_in? %>
        <%= link_to 'Log Out', destroy_user_session_url, method: :delete, class: "waves-effect waves-teal btn-flat" %>
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_url, class: "waves-effect waves-teal btn-flat" %>
      <% end %>

    </div>
  </div>
</div>